### ISSUE TITLE
Indexação de parâmetros nos eventos de Swap (transferência de Real Tokenizado)

### ISSUE THREAD

**Issue by raphaels10** [bacen/pilotord-kit-onboarding#12]
Investigando as ABIs dos contratos de Swap (SwapOneStep e SwapTwoSteps), notei que os eventos de SwapExecuted não têm parâmetros indexados:

`{
      "anonymous": false,
      "inputs": [
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "senderNumber",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "receiverNumber",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "sender",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "receiver",
          "type": "address"
        },
        {
          "indexed": false,
          "internalType": "uint256",
          "name": "amount",
          "type": "uint256"
        }
      ],
      "name": "SwapExecuted",
      "type": "event"
    }`

Considerando as práticas comuns de eventos indexados, e considerando que os participantes do piloto (provavelmente) irão ter alguma espécie de "listener" para replicar os eventos de transferência;swap em um banco de dados _offchain_, penso que seria interessante indexar os parâmetros dos eventos de Swap (e.g: indexar o **senderNumber** e o **receiverNumber** para que o participante consiga criar um filtro e captar somente os eventos de transferência onde ele é o pagador ou recebedor)

**Comment by Andrewsnobre** [comment]
> Investigando as ABIs dos contratos de Swap (SwapOneStep e SwapTwoSteps), notei que os eventos de SwapExecuted não têm parâmetros indexados:
> 
> `{ "anonymous": false, "inputs": [ { "indexed": false, "internalType": "uint256", "name": "senderNumber", "type": "uint256" }, { "indexed": false, "internalType": "uint256", "name": "receiverNumber", "type": "uint256" }, { "indexed": false, "internalType": "address", "name": "sender", "type": "address" }, { "indexed": false, "internalType": "address", "name": "receiver", "type": "address" }, { "indexed": false, "internalType": "uint256", "name": "amount", "type": "uint256" } ], "name": "SwapExecuted", "type": "event" }`
> 
> Considerando as práticas comuns de eventos indexados, e considerando que os participantes do piloto (provavelmente) irão ter alguma espécie de "listener" para replicar os eventos de transferência;swap em um banco de dados _offchain_, penso que seria interessante indexar os parâmetros dos eventos de Swap (e.g: indexar o **senderNumber** e o **receiverNumber** para que o participante consiga criar um filtro e captar somente os eventos de transferência onde ele é o pagador ou recebedor)

Gostei da sugestão, embora há ferramentas offchain como thegraph.com  para ler todos os eventos nos quais estamos interessados.

**Comment by matheusdsm** [comment]
Muito interessante essa sugestão!

É interessante de se pensar também em "transparência" com base neste contexto.
Analisando de uma forma não-técnica, um sistema que trabalha com câmbio de moedas é de suma importância que seja armazenado qualquer tipo de dado referente a transação. Isso é seguro tanto para o sistema, quanto para o usuário final.

Qualquer falta de dado ou breach do sistema é fatal.

Mais "transparência" ajuda a evitar uma série de problemas, tais como fraudes e golpes.

**Comment by aldenio** [comment]
Prezado @raphaels10,

Sua solicitação está sendo considerada pela equipe de desenvolvimento para ser incorporada em versões futuras.


obs: caso sua dúvida tenha sido respondida, favor encerrar a issue.
