### ISSUE TITLE
Cana de segurança para relatórios de vulnerabilidades

### ISSUE THREAD

**Issue by pedrosgmagalhaes** [bacen/pilotord-kit-onboarding#17]
Prezado(a)s,

Gostaria de consultar se há canais de comunicação para receber dados de vulnerabilidades de forma segura, de preferência com criptografia ponta a ponta. 

Obrigado,

Pedro Magalhães

**Comment by aldenio** [comment]
Prezado @pedrosgmagalhaes,

Agradecemos pelo seu interesse em contribuir com o Real Digital.

O  projeto Piloto do Real Digital é um ambiente de testes com dados fictícios, transações simuladas e acesso restrito aos participantes selecionados apenas pela RSFN. Ainda assim, qualquer vulnerabilidade encontrada pode ser encaminhada para o e-mail da equipe que será devidamente analisado: piloto.rd.tecnologia@bcb.gov.br.

obs: caso sua dúvida tenha sido resolvida, peço que encerre a issue.
