### ISSUE TITLE
Qual o significado da logo AngularJS no Piloto?

### ISSUE THREAD

**Issue by BrunooMoniz** [bacen/pilotord-kit-onboarding#18]
Vi que na [topologia da rede](https://github.com/bacen/pilotord-kit-onboarding/blob/main/topologia.png) está indicado a logo do AngularJS no ambiente offchain conectando ao RPC. Gostaria de entender o que significa? 
![image](https://github.com/bacen/pilotord-kit-onboarding/assets/44476844/300a87b0-a502-4030-bcd1-57767d4f38ad)

**Comment by thiagodeev** [comment]
Hey @BrunooMoniz, pelo o que entendi é só um exemplo de interface para se conectar ao RPC. No fórum deixou claro que isso não é necessário no Piloto, cabe ao participante implementar alguma interface caso queira (veja o vídeo do fórum do RD, no tempo de 20min30seg).
Em resumo, essa foto do Angular e de um smartphone é só um símbolo de uma interface que o participante pode implementar caso queira.
