### ISSUE TITLE
Banco Itaú implementou um nó na rede do Real Digital

### ISSUE THREAD

**Issue by pedrosgmagalhaes** [bacen/pilotord-kit-onboarding#19]
Prezado(a),

Analisando essa notícia, https://valor.globo.com/financas/noticia/2023/07/17/itau-instala-o-primeiro-no-da-rede-do-real-digital.ghtml

Gostaria de consultar, em qual camada foi instalado o nó da rede do Banco Itaú, considerando que existe uma topologia atual fornecido dentro das documentações, onde é demonstrado somente os nodes e validadores do Bacen e outras instituições públicas.

Assim como gostaria de consultar esse desenho atual da arquitetura em anexo, pode ser considerando uma fonte de estudos do arranjo do Real Digital, e em qual nó o Itaú está incluído.

<a href="https://ibb.co/N3B2xvD"><img src="https://i.ibb.co/N3B2xvD/1688391139184-1.png" alt="1688391139184-1" border="0"></a>

**Comment by aldenio** [comment]
Prezado @pedrosgmagalhaes,

Os nós dos participantes da rede do projeto piloto do Real Digital, irão se conectar ao sistema conforme apresentado na imagem  da [topologia](https://github.com/bacen/pilotord-kit-onboarding/blob/main/topologia.png). Nesta imagem você poderá observar a presença de 4 exemplos de participantes (A, B, C e D).

A imagem anexada na sua pergunta não representa a arquitetura adotada para o projeto Piloto do Real Digital.

obs: caso sua dúvida tenha sido respondida, peço que encerre a issue.

**Comment by pedrosgmagalhaes** [comment]
Entendi, somente para confirmar e encerrar o assunto: O nó do Itaú foi inserido dentro da topologia apresentada, mas é do tipo "full node" ou somente verificadores?

**Comment by BrunooMoniz** [comment]
@pedrosgmagalhaes pela topologia existe apenas 6 validadores (4 no Bacen de Brasília e 2 na Selic do Rio). Fora isso, todos os outros nós serão nós full node, atuando como RPC. Sendo assim não cabe ao Itau ou a qualquer outra instituição exercer o papel de validador. 

Depois veja essa imagem [aqui](https://besu.hyperledger.org/stable/public-networks/how-to/develop/client-libraries) na documentação da Besu que aponta o papel do RPC e mostra o nó minerador.

**Comment by pedrosgmagalhaes** [comment]
Excelente @BrunooMoniz! 

Ta super claro! Muito obrigado! Estou realizando uma rede da Hyperledger Besu em alguns computadores de forma simulada. A ideia é tentar criar um cenário refletido na estrutura das documentações que vocês estão disponibilizando.

Mas está super claro, muito obrigado!

**Comment by pedrosgmagalhaes** [comment]
@BrunooMoniz Essa imagem anexada da documentação da Besu está referenciando uma blockchain pública, né? Todos os full nodes possuem conexões RPCs ou os dados são retornados de uma pool de RPCs? Faz algum sentido meu raciocínio?

Eu imaginei um cenário onde o node do Itaú, poderia ter acesso e privilégio para obter dados de transações, incluindo os que não possuem origem e destino dentro de suas plataformas.

**Comment by BrunooMoniz** [comment]
A princípio não está implementada nenhuma solução de privacidade, então tudo que for validado pelos nós do Bacen será roteado para todos os nós da rede. Assim, até começarmos a testar as soluções de privacidade (agendado para setembro/23 até março/24) os nós vão compartilhar e ter visibilidade total de todas as transações, seja da sua plataforma ou não.

**Comment by pedrosgmagalhaes** [comment]
Excelente @BrunooMoniz! Vc é fera demais
