### ISSUE TITLE
Endereços e código fonte

### ISSUE THREAD

**Issue by Robsonsjre** [bacen/pilotord-kit-onboarding#2]
Pessoal, parabéns pelo lançamento! 
1) Serão disponibilizados os endereços e o código fonte dos contratos para o público?

2) Qual explorador de blocos será usado?

**Comment by itxtoledo** [comment]
Eu também gostaria do código fonte, afinal foi criado utilizando recursos públicos, deveria ser aberto para que todos pudessem auditar e sugerir melhorias. 

"Porque é que software criado com dinheiro dos contribuintes não é Software Livre?" - https://publiccode.eu/pt/

**Comment by cristianopolicarpo** [comment]
Acredito ser importante a disponibilização do código fonte dos contratos para criação de ambientes de testes e contribuição da comunidade em melhorias.

**Comment by BIP-Navarro** [comment]
Também reforço a importância da abertura desse código-fonte para o público.
Inclusive enviei um questionamento via e-mail durante o Fórum sobre Real Digital na semana passada (26/06) e a resposta que nos foi dada é que o código-fonte seria compartilhado nesse repositório. Ficamos no aguardo dessa liberação...

**Comment by itxtoledo** [comment]
Já que o BC não forneceu o source code, estou fazendo engenharia reversa por conta própria, mas já avancei bastante: https://github.com/itxtoledo/real-digital-reverse-engineering

É muito provável que este código não reflita a real funcionalidade dos contratos oficiais, mas é o que deu pra fazer.

**Comment by souzaclarissa** [comment]
> Pessoal, parabéns pelo lançamento!
> 
> 1. Serão disponibilizados os endereços e o código fonte dos contratos para o público?
> 2. Qual explorador de blocos será usado?

Os códigos-fonte dos contratos desenvolvidos para o Piloto do Real Digital serão publicados após finalizados os testes com os participantes do Piloto e ao término das auditorias de código necessárias. Para os testes previstos, as ABIs e as documentações já estão disponíveis neste canal. 

Os exploradores de bloco não serão determinados pelo Banco Central, cabendo a cada participante utilizar o explorador que melhor se adequar às suas necessidades. Importante ressaltar que os dados utilizados nos testes deverão ser fictícios e não devem ser armazenados ou replicados para ambientes computacionais alheios aos das instituições autorizadas conforme regulamentação vigente.

**Comment by souzaclarissa** [comment]
> Os códigos-fonte dos contratos desenvolvidos para o Piloto do Real Digital serão publicados após finalizados os testes com os participantes do Piloto e ao término das auditorias de código necessárias. Para os testes previstos, as ABIs e as documentações já estão disponíveis neste canal.

Os códigos-fonte dos contratos desenvolvidos para o Piloto do Real Digital serão publicados após finalizados os testes com os participantes do Piloto e ao término das auditorias de código necessárias.

**Comment by pedrosgmagalhaes** [comment]
Pra quem tem interesse em testar as funcionalidades do ABI. Eu também disponibilizei um smart contract com testes unitários utilizando engenharia reversa. Dá para testar as funcionalidades em um ambiente simulado próximo ao que deve ser disponibilizado.

Github: [https://github.com/ioralabs/realdigital_smartcontracts](https://github.com/ioralabs/realdigital_smartcontracts)
YouTube Tutorial Português: [https://youtu.be/VydDQzOJTmQ](https://youtu.be/VydDQzOJTmQ)

**Comment by aldenio-bcb** [comment]
Prezado @Robsonsjre,

Caso a sua dúvida tenha sido respondida, favor fechar a issue.
