### ISSUE TITLE
ABI for RealDigitalDefaultAccount is inconsistent with documentation

### ISSUE THREAD

**Issue by krzysztof-cywinski** [bacen/pilotord-kit-onboarding#22]
Hello,
the constructor [ABI](https://github.com/bacen/pilotord-kit-onboarding/blob/main/abi/RealDigitalDefaultAccount.json)
```json
  {
    "inputs": [
      {
        "internalType": "contract RealDigital",
        "name": "token",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  }
```
does not match [the documentation](https://github.com/bacen/pilotord-kit-onboarding/blob/main/RealDigitalDefaultAccount.md#constructor) for `RealDigitalDefaultAccount`.

Which one is correct and what's the intent of passing `RealDigital` to `RealDigitalDefaultAccount`?

**Comment by aldenio** [comment]
Prezado @krzysztof-cywinski ,

O arquivo da [ABI](https://github.com/bacen/pilotord-kit-onboarding/blob/main/abi/RealDigitalDefaultAccount.json) foi atualizado, agradecemos sua colaboração. 

A lógica dos contratos será divulgada em breve com a liberação dos códigos fonte.

obs: caso sua dúvida tenha sido respondida, peço que encerre a issue.

**Comment by krzysztof-cywinski** [comment]
Obrigado @aldenio
