### ISSUE TITLE
Endereço contratos

### ISSUE THREAD

**Issue by tzdesing** [bacen/pilotord-kit-onboarding#25]
Existe a previsão de quando e como serão disponibilizados os endereços dos contratos para os participantes do piloto?

**Comment by thiagodeev** [comment]
@tzdesing , pelo comentário da Clarissa na issue número 2 (https://github.com/bacen/pilotord-kit-onboarding/issues/2#issuecomment-1620821784) os códigos dos contratos só serão liberados após o término do Piloto, depois se serem feitas auditorias e testes com os participantes. Ela deixou claro que para o Piloto apenas a ABI e a documentação já seria o suficiente para o participante conseguir interagir e testar os contratos, então imagino que nem para os participantes o código será liberado.

**Comment by BrunooMoniz** [comment]
@tzdesing pelo o que entendi, os participantes vão conseguir os endereços chamando o [AddressDiscovery](https://github.com/bacen/pilotord-kit-onboarding/blob/main/AddressDiscovery.md) mas agora, pra isso eles precisam do endereço desse contrato rsrs... Que até então não foi divulgado aqui no repositório.

**Comment by thiagodeev** [comment]
@tzdesing perdão, respondi errado 😅. Não li direito e tinha entendido que a pergunta era sobre os códigos fontes.

Estou junto contigo nessa dúvida de quando serão divulgados os endereços.

**Comment by tzdesing** [comment]
Conseguimos descobrir, monitorando as transações na rede e efetuando testes de tentativa e erro.
