### ISSUE TITLE
Diferenciação DVt e MEt no RealTokenizado 

### ISSUE THREAD

**Issue by BrunooMoniz** [bacen/pilotord-kit-onboarding#26]
Ao revisar os [documentos relacionados à implementação do contrato para o Real Tokenizado](https://github.com/bacen/pilotord-kit-onboarding/blob/main/RealTokenizado.md), notei que, embora sejam mencionados os termos "DVt" e "MEt", não está claro como eles são distintos um do outro no contexto do contrato. Considerando que ambos são ativos com comportamentos potencialmente diferentes, essa distinção é crucial.

Estou curioso sobre o papel do ponto de "Reserva" e como ele se relaciona com esses dois termos. Adicionalmente, estou avaliando a possibilidade de implementar um _ratio_ no contrato que conecte o depósito compulsório à quantidade de Real Tokenizado emitido pela instituição. Seria possível esclarecer estas questões?

**Comment by aldenio** [comment]
Prezado @BrunooMoniz,

Os Termos DVt e MEt são as versões tokenizadas do Depósito a Vista e da Moeda Eletrônica, respectivamente. Eles diferem entre si pela natureza do ativo representado. Dúvidas de negócio podem ser encaminhadas para o e-mail: piloto.rd@bcb.gov.br

Observe que o contrato do [RealDigital](https://github.com/bacen/pilotord-kit-onboarding/blob/main/RealDigital.md) será o responsável pela gestão dos tokens de Real Digital e o contrato do [RealTokenizado](https://github.com/bacen/pilotord-kit-onboarding/blob/main/RealTokenizado.md) será responsável pela gestão dos tokens de uma instituição participante, esse token poderá ser tanto um DVt quanto um MEt, a depender da natureza do ativo representado.

A princípio não há previsão de depósito compulsório no DREX.

obs: caso sua dúvida tenha sido respondida, favor encerrar a issue.
