### ISSUE TITLE
Os motivos de reversão não serão ativados no besu (--revert-reason-enabled) ?

### ISSUE THREAD

**Issue by viniciusxyz** [bacen/pilotord-kit-onboarding#27]
Estou realizando alguns testes com contratos que implementam a abi divulgada em um cluster besu configurado conforme o [config.toml](https://github.com/bacen/pilotord-kit-onboarding/blob/main/config.toml)  e por curiosidade comecei a testar cenários de falha e notei que o revert-reason sempre vem vázio, dando uma olhada na documentação do besu vi que isso precisa ser ativo como podemos [ver aqui](https://besu.hyperledger.org/stable/private-networks/how-to/send-transactions/revert-reason#enable-revert-reason), porém no [config.toml](https://github.com/bacen/pilotord-kit-onboarding/blob/main/config.toml) do repositório não existe esse parâmetro, quando houverem regras de negócio não atendidas como por exemplo o cliente A não tem saldo suficiente para transferir para o cliente B, como poderemos consultar sem o reason ? Haverá algum evento com essa informação ?

**Comment by aldenio** [comment]
Prezado @viniciusxyz,

Obrigado por sua colaboração, ativamos o revert-reason no config.toml.

ps: Caso sua dúvida tenha sido respondida, favor encerrar o Issue.
