### ISSUE TITLE
CBDCAccessControl & AddressDiscovery ABIs

### ISSUE THREAD

**Issue by begrossi** [bacen/pilotord-kit-onboarding#3]
É possível disponibilizar as ABIs dos contratos CBDCAccessControl e AddressDiscovery? 
Obrigado.

**Comment by aldenio** [comment]
Prezado @begrossi,

A ABI do contrato [AddressDiscovery](https://github.com/bacen/pilotord-kit-onboarding/blob/main/abi/AddressDiscovery.json) acaba de ser publicada.

O contrato CBDCAccessControl é abstrato e sua ABI está presente nos arquivos [RealDigital.json](https://github.com/bacen/pilotord-kit-onboarding/blob/main/abi/RealDigital.json) e [RealTokenizado.json.](https://github.com/bacen/pilotord-kit-onboarding/blob/main/abi/RealTokenizado.json).
