### ISSUE TITLE
Enforcement no permissionamento de nós

### ISSUE THREAD

**Issue by gabrielsdev** [bacen/pilotord-kit-onboarding#32]
Haverá algum tipo de enforcement no permissionamento de nós da rede?

Caso um nó esteja listado no smart contract de permissionamento de nós mas não habilite o permissionamento de nó no config.toml, este nó pode se conectar com um outro fora da lista de permissionamento e, assim, permitir que nós despermissionados participem da rede.

Desse modo, será desenvolvido algum tipo de reforço para o permissionamento ou as configurações de firewall e permissionamento são consideradas suficientes? #29

**Comment by aldenio** [comment]
Prezado @gabrielsdev ,

Estamos cientes da situação relativa ao permissionamento via arquivo config.toml e estamos considerando o uso de permissionamento por smart contract, permissionamento das wallets, o uso de TLS e firewalls como mecanismos de proteção, além da monitoração ativa dos nós da rede. Nossa equipe técnica ainda não chegou a um consenso se os mecanismos aplicados são ou não suficientes para garantir o correto funcionamento da rede.

**ps.1**: Caso alguém tenha sugestões adicionais para essa situação, estamos abertos a ouvir.
**ps.2**: Vale ressaltar que estamos tratando do projeto piloto do real digital, e que uma de suas funções é identificar pontos de atenção para que possamos mapear controles que terão que ser implementados quando passarmos a desenvolver o sistema que irá para produção.

No caso da sua dúvida ter sido respondida, peço que feche esta _issue_.

**Comment by gabrielsdev** [comment]
Obrigado pela resposta! No entanto, mesmo com a utilização do permissionamento onchain, utilização de TLS, firewalls e monitoração ativa dos nós, qualquer instituição ainda seria capaz de conectar a um nó fora da rede (não permissionado) e permitir que esse nó tenha acesso a todos os blocos. Acredito ser um ponto de falha para a rede do DREX e que precisa de certa atenção.
