### ISSUE TITLE
Eventos da ABI SwapTwoSteps faltando parâmetro proposalId

### ISSUE THREAD

**Issue by r1c4rd0y** [bacen/pilotord-kit-onboarding#34]
Os eventos SwapStarted e SwapExecuted da ABI SwapTwoSteps não contém o parâmetro proposalId conforme especificado na documentação.

**Comment by aldenio** [comment]
Prezado @r1c4rd0y, 

Agradecemos sua colaboração, nossa equipe já está avaliando sua PR #36, trataremos deste assunto lá.
