### ISSUE TITLE
Permissionamento de transações

### ISSUE THREAD

**Issue by gabrielsdev** [bacen/pilotord-kit-onboarding#39]
De acordo com as configurações contidas no config.toml, não está sendo usado o permissionamento de transações na rede. Ele será usado posteriormente, ou de fato não será utilizado?

Com o permissionamento de transações configurado, seria possível gerenciar quem pode transacionar na rede e, até mesmo, quem pode fazer deploy na rede. Acredito ser uma ferramenta poderosa para condicionar as transações a um conjunto de regras. Como quem pode enviar, quem pode receber, até qual valor, até qual quantidade de gas etc.

Está previsto algo desse tipo na rede?

**Comment by sandrogomes94** [comment]
Aonde você viu permissionamento de transações na rede?

**Comment by aguinaldotupy** [comment]
@gabrielsdev 

É sobre isso que se refere?
https://github.com/bacen/pilotord-kit-onboarding/blob/fef77593254744e8c975ca548d8a9f7f8731efd1/config.toml#L63-L66

**Comment by gabrielsdev** [comment]
> Aonde você viu permissionamento de transações na rede?

Exatamente, não está sendo utilizado permissionamento de transações no DREX. Porém, o [besu disponibiliza essa funcionalidade](https://besu.hyperledger.org/private-networks/reference/cli/options#permissions-accounts-contract-enabled).

**Comment by gabrielsdev** [comment]
> @gabrielsdev 
> 
> 
> 
> É sobre isso que se refere?
> 
> https://github.com/bacen/pilotord-kit-onboarding/blob/fef77593254744e8c975ca548d8a9f7f8731efd1/config.toml#L63-L66

Não. Essas CLI Options que mencionou dizem respeito ao permissionamento de nós.

As CLI Options abaixo (somadas a essa: --permissions-nodes-contract-version=<versão>) habilitam o permissionamento de transações na rede:

--permissions-accounts-contract-enabled=true

--permissions-accounts-contract-address=<endereço-do-contrato>

**Comment by aldenio** [comment]
Prezado @gabrielsdev,

Estamos cientes dessa possibilidade, porém decidimos estudar com profundidade essa solução, dentre outras, num segundo momento.
