### ISSUE TITLE
RealDigitalDefaultAccount - padronização de input names entre getters e setters

### ISSUE THREAD

**Issue by alexcostars** [bacen/pilotord-kit-onboarding#4]
O primeiro input para a function `addDefaultAccount` do ABI `RealDigitalDefaultAccount.json` está especificando o `name` como:
```json
"name": "cnpj8",
```

Já a function `defaultAccount` não especifica qual é o `name` de seu input:
```json
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "defaultAccount",
    ...
  },
```

Sugestão: se o input esperado para `defaultAccount` realmente for um `cnpj8`, sugiro especificá-lo para dar clareza ao que se espera como entrada para execução da function.

**Comment by aldenio-bcb** [comment]
A função getter "defaultAccount" apresentada na ABI é gerada automaticamente pelo ferramental, a partir de um mapping:
mapping (uint256 => address) public defaultAccount; O mapping não possui nome de parâmetro para consulta.

A função "addDefaultAccount" apresentada na ABI é de fato uma função do contrato, e possui um nome para seu parâmetro.
Por este motivo há uma diferença na apresentação dessas funções na ABI.

Para atender a esta demanda, seria necessária a implementação de uma função redundante, do tipo getter com um parâmetro nomeado, porém, seguindo as melhores práticas da engenharia de softwares, optamos por manter o código simples e conciso.

**Comment by alexcostars** [comment]
Entendo e concordo com seu comentário @aldenio-bcb,

submeti o pull request https://github.com/bacen/pilotord-kit-onboarding/pull/15 propondo uma alteração que não afeta o código fonte do contrato.
