### ISSUE TITLE
Falta tratamento das informações referente aos contratos

### ISSUE THREAD

**Issue by 0x5FE** [bacen/pilotord-kit-onboarding#41]
Pelo que se observa no código, os endereços que na prática seriam endereços reais dos contratos, estão sendo passados direto no código, o que pode acarretar em vulnerabilidade. Melhor prática seria isolar em variáveis ​​de ambiente ou outro mecanismo para armazenar esses endereços a parte, protegendo as informações.

![Sem título](https://github.com/bacen/pilotord-kit-onboarding/assets/65371336/98505d54-911e-4d5d-b6a0-bbd2c11ed72a)

**Comment by thiagodeev** [comment]
Olá @0x5FE.
No [README.md](https://github.com/bacen/pilotord-kit-onboarding/blob/701177989cf7d9fc765c5583f272ea98e52c74a6/exemplos/README.md) que descreve o intuito dos exemplos diz:

>Os participantes são livres pra desenvolverem a interação com os contratos inteligentes da forma que bem entenderem.

> Esse código foi testado mas não foi feita nenhuma auditoria ou análise de vulnerabilidade. Não recomendamos o uso em produção, especialmente o uso de chaves privadas no arquivo de configuração do Hardhat.

São apenas exemplos para se conectar e testar os Smart Contracts na rede do Piloto, não sendo recomendados para produção.

**Comment by 0x5FE** [comment]
@thiagodeev Certo, com relação ao Drex, será disponibilizado em repositório também para análise?

**Comment by thiagodeev** [comment]
@0x5FE não entendi ao certo, quis dizer os códigos fontes dos contratos inteligentes usados nesse piloto do DREX?
Se sim, dê uma olhada nesse [comentário](https://github.com/bacen/pilotord-kit-onboarding/issues/2#issuecomment-1620821784) numa issue cuja a pergunta era também sobre os códigos fontes.

Em suma, de acordo com o BACEN, serão disponibilizados somente após o término do Piloto.

**Comment by 0x5FE** [comment]
@thiagodeev valeu thiago
