### ISSUE TITLE
ABI TPFt

### ISSUE THREAD

**Issue by tzdesing** [bacen/pilotord-kit-onboarding#43]
O ABI (TPFt.json) ainda não foi disponibilizado, apesar do contrato já ter sido deployado na rede e as interfaces terem sido disponibilizadas. Será disponibilizado em breve?

**Comment by aldenio** [comment]
Prezado @tzdesing,

O contrato de TPFt é de uso privativo e gestão exclusiva do Selic. Portanto, a princípio, a sua interface (ABI) não será divulgada.

obs: Caso sua dúvida tenha sido respondida, favor encerrar a issue.

**Comment by aldenio** [comment]
Prezado @tzdesing,

Houve uma mudança de entendimento da equipe de desenvolvimento e a ABI ITPFt.json será publicada.
