### ISSUE TITLE
Contrato sem Roles apropriadas

### ISSUE THREAD

**Issue by tzdesing** [bacen/pilotord-kit-onboarding#46]
Os contratos SwapOneStep e SwapTwoSteps não possuem as roles apropriadas (BURN , MINT, MOVE) para efetuar as transações necessárias nos tokens dos participantes e verificamos que as Roles só podem ser concedidas pelo BC.

**Comment by aldenio** [comment]
Prezado @tzdesing ,

Essa questão está sendo tratada pela equipe de desenvolvimento. Avisarei aqui quando as mudanças forem implantadas.

**Comment by aldenio** [comment]
Prezado @tzdesing,

As roles foram atribuídas aos contratos no momento do deploy dos contratos na rede.


obs: caso sua pergunta tenha sido respondida, favor encerrar a issue.
