### ISSUE TITLE
Nomenclatura Métodos

### ISSUE THREAD

**Issue by tzdesing** [bacen/pilotord-kit-onboarding#47]
A nomenclatura dos métodos "trade", na interface ITPFtOperation1052, gera problemas em diversas bibliotecas, apesar da assinatura diferente.
Sugiro a alteração da nomenclatura para tradeByAdresses e tradeByCNPJ8.
Grato

**Comment by Firminodeassis** [comment]
Nomenclaturas diferentes porém sentidos os mesmos mecanismo iguais.o biticoins.es as fórmulas.nomencraticas . diversificado....pix.ted e o.i.p.

**Comment by Firminodeassis** [comment]
Financiamento consórcio e outros és o mesmo sistema e nomes diversos diferentes porém com mesmo sistema de significado

**Comment by Firminodeassis** [comment]
Tenkil Firmino

**Comment by aldenio** [comment]
Prezado @tzdesing,

Para o piloto, implementamos desta maneira, já que a sobrecarga das funções não impede o seu uso. 
Vamos considerar a troca dos nomes em uma versão posterior, e agradecemos sua contribuição.

ps: Caso sua pergunta tenha sido respondida. favor encerrar a issue.
