### ISSUE TITLE
Solicitação de Esclarecimento sobre o Contrato "ITPFt"

### ISSUE THREAD

**Issue by cristianopolicarpo** [bacen/pilotord-kit-onboarding#51]
Olá equipe de desenvolvimento,

Estou revisando a documentação do contrato "ITPFt" no projeto e estou interessado em entender melhor sua função e como ele se encaixa no ecossistema geral do projeto. A documentação fornece detalhes sobre os métodos e eventos do contrato, mas não especifica se este é um contrato independente ou uma interface.

Gostaria de solicitar mais informações sobre o contrato "ITPFt" para esclarecer os seguintes pontos:

1. Este contrato "ITPFt" é uma interface ou um contrato independente? Se for uma interface, quais contratos implementam essa interface?

2. Qual é o propósito principal do "ITPFt" dentro do sistema? Como ele se relaciona com outros contratos ou partes do sistema?

Qualquer informação adicional que você possa fornecer sobre o contrato "ITPFt" seria apreciada.

Obrigado pela ajuda!

Atenciosamente,
Cristiano

**Comment by begrossi** [comment]
Cristiano, o ITPFt é um token ERC1155 que representa os diversos títulos emitidos pela STN..

**Comment by thiagodeev** [comment]
Exato, é como o Cristiano comentou. Para mais descrições além do que se encontra na documentação aqui do repositório e das documentações existentes do padrão ERC1155, você pode ver o que foi dito sobre esses contratos no fórum que teve nesta quarta-feira. Aqui está o link (se fala sobre o contrato por volta de 30min do vídeo):
https://www.youtube.com/watch?v=vRbCvwRNxLk

**Comment by aldenio** [comment]
Prezado @cristianopolicarpo,

ITPFt é uma interface utilizada para definições como tipos de dados e eventos necessários para a operação de títulos públicos federais tokenizados (TPFt). Ela é implementada no contrato TPTt que estende a especificação ERC1155.

ps: caso sua dúvida tenha sido respondida, favor encerrar a issue.

**Comment by mesquitaoliveira** [comment]
Olá! Será disponibilizado a ABI de `TPFtAccessControl`? Dúvida o contrato `ITPFt` não deveria herdar `TPFtAccessControl` ?
