### ISSUE TITLE
Permissão do SwapTwoStepsReserve ao Real Tokenizado

### ISSUE THREAD

**Issue by gabrielsdev** [bacen/pilotord-kit-onboarding#53]
De acordo com a [documentação do real digital sobre o método _beforeTokenTransfer](https://github.com/bacen/pilotord-kit-onboarding/blob/main/RealDigital.md#_beforetokentransfer), toda transação de transferência de tokens passa por uma checagem de acesso do remetente e destinatário que verifica se ambos estão autorizados a receber/enviar tokens. 
Dessa forma, toda autoridade de um contrato de real tokenizado pode impedir o uso do SwapTwoStepsReserve quando desabilitar o endereço do contrato de receber tokens com o método [disableAccount](https://github.com/bacen/pilotord-kit-onboarding/blob/main/CBDCAccessControl.md#disableaccount) do qual a autoridade possui permissão para executar.

Esse é de fato o comportamento esperado?

**Comment by aldenio** [comment]
Prezado @gabrielsdev,

Sim, este é o comportamento esperado. Cada instituição determina que contas podem ou não receber recursos na plataforma.

obs: caso sua dúvida tenha sido respondida, favor encerrar a issue.
