### ISSUE TITLE
Congelar saldo em operações de swap

### ISSUE THREAD

**Issue by gabrielsdev** [bacen/pilotord-kit-onboarding#55]
A [documentação que descreve o papel de congelamento para o real digital](https://github.com/bacen/pilotord-kit-onboarding/blob/main/CBDCAccessControl.md#freezer_role) sugere a utilização do congelamento de saldo para o swap de dois passos. No entanto, ao congelar o saldo do cliente da instituição pagadora, a instituição recebedora teria que descongelar o saldo da outra instituição para executar o swap, o que é inviável porque a outra instituição não deveria ter esta autorização.

Essa sugestão está correta?

**Comment by aldenio** [comment]
Prezado @gabrielsdev,

 De fato a primeira versão do contrato de SWAP continha a função de congelamento que era gerenciada pelo próprio contrato de SWAP. Essa mecânica foi movida para o contrato swap two steps reserve. Uma nova versão dos contratos está em construção. Porém, pode ficar tranquilo que não haverá impactos nos testes.

obs: caso sua dúvida tenha sido respondida, favor encerrar a issue.
