### ISSUE TITLE
Divergência em casas decimais no preço unitário do TPFt 

### ISSUE THREAD

**Issue by cristianopolicarpo** [bacen/pilotord-kit-onboarding#60]
O Real Digital e o Real Tokenizado têm valores definidos com 2 casas decimais como informado em [smartcontracts.md](https://github.com/bacen/pilotord-kit-onboarding/blob/main/smartcontracts.md). Entretanto os documentos [ITPFtOperation1002.md](https://github.com/bacen/pilotord-kit-onboarding/blob/main/ITPFtOperation1002.md) e [ITPFtOperation1052.md](https://github.com/bacen/pilotord-kit-onboarding/blob/main/ITPFtOperation1052.md) mencionam o preço unitário do TPFt com 8 casas decimais.

**Comment by aldenio** [comment]
Prezado @cristianopolicarpo,  

Os títulos públicos federais são negociados com 6 ou 8 casas decimais. Esse número de decimais é essencial para a contabilização, pagamento de juros, resgates e amortizações, em suma, vários processos essenciais dos TPF.
O valor de uma operação é o produto do Preço Unitário com a quantidade, esse valor é então truncado para duas casas decimais. Caso ocorram perdas financeiras devido à política de arredondamento, a regra atual define que o acerto será realizado na última parcela.

ps:  caso sua dúvida tenha sido respondida, favor encerrar a issue.
