### ISSUE TITLE
Evento de proposta expirada

### ISSUE THREAD

**Issue by gabrielsdev** [bacen/pilotord-kit-onboarding#61]
O [evento ExpiredProposal](https://github.com/bacen/pilotord-kit-onboarding/blob/main/SwapTwoSteps.md#expiredproposal) é emitido na chamada de qual método dos contratos de SwapTwoSteps?

**Comment by thiagodeev** [comment]
@gabrielsdev, existe também a sessão de [Discussões](https://github.com/bacen/pilotord-kit-onboarding/discussions) aqui no repositório, creio que é mais adequada para sanar dúvidas do tipo

**Comment by gabrielsdev** [comment]
Obrigado pela sugestão @thiagodeev! Há um tempo enviei um tópico por lá, mas tenho percebido que as questões levantadas nessa sessão tem um tempo de resposta menor e maior visibilidade. Além disso, considero que meu questionamento seja mais adequado para essa sessão, e explico: um contrato, por si só, não é capaz de emitir um evento após um determinado período, é necessário que ele seja acionado para isso. E também não é possível emitir um evento quando uma transação é revertida. Dessa forma, esse evento não cumpre o seu papel, ao menos ao que ele se propõe a fazer.

**Comment by aldenio** [comment]
Prezado @gabrielsdev,

De fato esse evento existe mas não está sendo emitido em nenhum lugar. Em vez de emiti-lo a equipe optou por reverter a transação, mas ainda não removeu o evento. Este evento será removido da ABI numa versão futura.

ps: caso sua dúvida tenha sido respondida, favor encerrar a issue.
