### ISSUE TITLE
As configurações do config.toml precisam ser iguais as descritas no arquivo do projeto ?

### ISSUE THREAD

**Issue by viniciusxyz** [bacen/pilotord-kit-onboarding#64]
Eu não entendi muito bem se haverá algum tipo de auditoria sobre as configurações do nó do ledger obrigando seguir as configurações do [config.toml do repositório](https://github.com/bacen/pilotord-kit-onboarding/blob/main/config.toml) ou se há configurações que serão opcionais para as instituições, por exemplo:

```
metrics-enabled=false
graphql-http-enabled=false
rpc-ws-enabled=false
```

Essas configurações realmente precisam estar desabilitadas? Ou isso é algo que a instituição que subiu o nó irá decidir?

**Comment by aldenio** [comment]
Prezado @viniciusxyz,

Primeiramente, obrigado por sua contribuição. 

Sobre auditorias: a princípio não haverá qualquer tipo de auditoria nos sobre as configurações dos nós do ledger. O projeto PILOTO do Real Digital (DREX) é um projeto de pesquisa, estudo e testes, onde todos os participantes são parceiros voluntários. 

Existem alguns parâmetros no arquivo config.toml que são necessários para a conexão do nó na rede e para o correto funcionamento da rede em si. Porém, os 3 parâmetros mencionados na issue são de livre escolha dos participantes.

Numa versão futura da documentação, nós vamos destacar quais parâmetros são "obrigatórios" e quais são "opcionais". 

ps: caso sua pergunta tenha sido respondida, favor encerrar a issue.
