### ISSUE TITLE
"Error: Request failed with status code 500" ao fazer chamada deposit - Starlight

### ISSUE THREAD

**Issue by julianarhk** [bacen/pilotord-kit-onboarding#72]
Olá,

Nossa carteira tem saldo suficiente para transferir Real Digital.

Foram realizados os depósitos para o contrato Escrow (os dois commitments não gastos necessários para a transferência).

Na hora de fazer a chamada de transferência tenho o seguinte erro:

![Captura de tela 2024-05-13 162439](https://github.com/bacen/pilotord-kit-onboarding/assets/102271194/3a13ac02-f178-4dcd-a7ad-c8f59566665a)

Os parâmetros do nó Besu já foram configurados e o nó foi reiniciado, porém, o erro persiste.

Alguém pode ajudar?

Obrigada.

**Comment by aldenio** [comment]
Juliana, 

Por favor, envie um email para tecnologia.piloto.drex@bcb.gov.br com os passos para reproduzir o erro.
Vamos te responder com as orientações necessárias para resolver seu problema.

**Comment by tzdesing** [comment]
@aldenio  Problema resolvido, obrigado
